// Common Pokémon move translations
export const moveTranslations: Record<string, { en: string; fr: string }> = {
  "tackle": { en: "Tackle", fr: "Charge" },
  "thunderbolt": { en: "Thunderbolt", fr: "Tonnerre" },
  "water-gun": { en: "Water Gun", fr: "Pistolet à Eau" },
  "ember": { en: "Ember", fr: "Flammèche" },
  "flamethrower": { en: "Flamethrower", fr: "Lance-Flammes" },
  "ice-beam": { en: "Ice Beam", fr: "Laser Glace" },
  "psychic": { en: "Psychic", fr: "Psychique" },
  "earthquake": { en: "Earthquake", fr: "Tremblement" },
  "shadow-ball": { en: "Shadow Ball", fr: "Boule Ombre" },
  "hydro-pump": { en: "Hydro Pump", fr: "Surf" },
  "blizzard": { en: "Blizzard", fr: "Tempête de Neige" },
  "thunder": { en: "Thunder", fr: "Tonnerre" },
  "dragon-claw": { en: "Dragon Claw", fr: "Griffe Dragon" },
  "earthquake": { en: "Earthquake", fr: "Tremblement" },
  "stone-edge": { en: "Stone Edge", fr: "Tranchant Rocheux" },
  "sludge-bomb": { en: "Sludge Bomb", fr: "Bombe Boue" },
  "poison-powder": { en: "Poison Powder", fr: "Poudre Toxique" },
  "confusion": { en: "Confusion", fr: "Confusion" },
  "gust": { en: "Gust", fr: "Vent Violent" },
  "wing-attack": { en: "Wing Attack", fr: "Coup d'Aile" },
  "double-team": { en: "Double Team", fr: "Double Équipe" },
  "recover": { en: "Recover", fr: "Récupération" },
  "iron-tail": { en: "Iron Tail", fr: "Queue de Fer" },
  "bite": { en: "Bite", fr: "Morsure" },
  "quick-attack": { en: "Quick Attack", fr: "Attaque Rapide" },
  "pound": { en: "Pound", fr: "Frappe" },
  "scratch": { en: "Scratch", fr: "Griffe" },
  "grow": { en: "Grow", fr: "Croissance" },
  "peck": { en: "Peck", fr: "Coup de Bec" },
  "metal-claw": { en: "Metal Claw", fr: "Griffe Acier" },
  "swift": { en: "Swift", fr: "Vive-Attaque" },
  "withdraw": { en: "Withdraw", fr: "Repli" },
  "water-pulse": { en: "Water Pulse", fr: "Impulsion Eau" },
  "rain-dance": { en: "Rain Dance", fr: "Danse Pluie" },
  "sunny-day": { en: "Sunny Day", fr: "Beau Temps" },
  "sandstorm": { en: "Sandstorm", fr: "Tempête de Sable" },
  "hail": { en: "Hail", fr: "Grêle" },
  "protect": { en: "Protect", fr: "Protection" },
  "reflect": { en: "Reflect", fr: "Reflet" },
  "light-screen": { en: "Light Screen", fr: "Écran Lumière" },
  "aurora-beam": { en: "Aurora Beam", fr: "Rayon Aurore" },
  "energy-ball": { en: "Energy Ball", fr: "Boule Énergie" },
  "focus-blast": { en: "Focus Blast", fr: "Tir de Précision" },
  "meteor-mash": { en: "Meteor Mash", fr: "Frappe Météore" },
  "close-combat": { en: "Close Combat", fr: "Riposte" },
  "high-jump-kick": { en: "High Jump Kick", fr: "Coup Haut" },
  "stone-edge": { en: "Stone Edge", fr: "Tranchant Rocheux" },
  "rock-slide": { en: "Rock Slide", fr: "Éboulement" },
  "rock-throw": { en: "Rock Throw", fr: "Lancer de Roche" },
  "power-gem": { en: "Power Gem", fr: "Gemme de Pouvoir" },
  "bullet-punch": { en: "Bullet Punch", fr: "Poing Éclair" },
  "mach-punch": { en: "Mach Punch", fr: "Poing Mach" },
  "vacuum-wave": { en: "Vacuum Wave", fr: "Onde de Choc" },
  "focus-energy": { en: "Focus Energy", fr: "Concentration" },
  "calm-mind": { en: "Calm Mind", fr: "Sérénité" },
  "swords-dance": { en: "Swords Dance", fr: "Danse Épée" },
  "dragon-dance": { en: "Dragon Dance", fr: "Danse Dragon" },
  "work-up": { en: "Work Up", fr: "Effort" },
  "barrier": { en: "Barrier", fr: "Barrière" },
  "iron-defense": { en: "Iron Defense", fr: "Défense Fer" },
  "acid-armor": { en: "Acid Armor", fr: "Armure Acide" },
  "amnesia": { en: "Amnesia", fr: "Amnésie" },
  "curse": { en: "Curse", fr: "Malédiction" },
  "trick-room": { en: "Trick Room", fr: "Salle Truquée" },
  "stealth-rock": { en: "Stealth Rock", fr: "Piège de Roche" },
  "spikes": { en: "Spikes", fr: "Pics Toxiques" },
  "toxic-spikes": { en: "Toxic Spikes", fr: "Pics Toxiques" },
  "leech-seed": { en: "Leech Seed", fr: "Graine Parasite" },
  "growth": { en: "Growth", fr: "Croissance" },
  "synthesis": { en: "Synthesis", fr: "Synthèse" },
  "photosynthesis": { en: "Photosynthesis", fr: "Photosynthèse" },
  // Ajoutez plus de traductions selon vos besoins
}

export function getMoveName(moveName: string, language: "en" | "fr" = "en"): string {
  const translation = moveTranslations[moveName.toLowerCase()]
  if (!translation) {
    // Fallback: capitalize the original name
    return moveName.split("-").map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(" ")
  }
  return translation[language]
}
